export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';
export const FETCH_FAMILY = 'FETCH_FAMILY';
export const LISTEN_TO_SELECTED_PERSON = 'LISTEN_TO_SELECTED_PERSON';
export const CLEAR_SELECTED_PERSON = 'CLEAR_SELECTED_PERSON';
export const CLEAR_FAMILYS = 'CLEAR_FAMILYS';
export const RETAIN_FAMILY_STATE = 'RETAIN_FAMILY_STATE';
